FROM rclone/rclone:v1.72-stable AS rclone

FROM debian:trixie-slim

COPY --from=rclone /usr/local/bin/rclone /usr/bin/rclone

RUN apt-get update && \
    apt-get install -y ca-certificates fuse3 tzdata && \
    echo "user_allow_other" >> /etc/fuse.conf && \
    rm -rf /var/lib/apt/lists/*

COPY mzworker-go-linux-amd64 /usr/local/bin/mzworker-go
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /usr/local/bin/mzworker-go /entrypoint.sh && ln -sf /usr/local/bin/mzworker-go /usr/local/bin/mzworker

ENTRYPOINT ["/entrypoint.sh"]
