FROM rclone/rclone:v1.72-stable

RUN echo "**** Install Dependencies ****" && \
    apt-get update && \
    apt-get install -y \
        ca-certificates \
        fuse3 \
        tzdata && \
    echo "Enable user_allow_other in fuse" && \
    echo "user_allow_other" >> /etc/fuse.conf && \
    rm -rf /var/lib/apt/lists/*

COPY mzworker-linux-amd64 /usr/local/bin/mzworker
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
